//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iv_de1Entities : DbContext
    {
        public iv_de1Entities()
            : base("name=iv_de1Entities")
        {
        }
        
        public static iv_de1Entities GetContext()
        {
            return new iv_de1Entities();
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DocumentsByService> DocumentsByService { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<ProductPhotos> ProductPhotos { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSales> ProductSales { get; set; }
        public virtual DbSet<ServiceClient> ServiceClient { get; set; }
        public virtual DbSet<ServicePhotos> ServicePhotos { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
    }
}
