//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int Id { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ClientServiceId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ServiceClient ServiceClient { get; set; }
    }
}
