//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.ServiceClient = new HashSet<ServiceClient>();
            this.ServicePhotos = new HashSet<ServicePhotos>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Duration { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Discount { get; set; }

        public string ImagePath
        {
            get
            {
                string fullPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Images", Image);

                return new Uri(fullPath).AbsoluteUri;
            }
        }

        public string checkDiscount
        {
            get
            {
                if (this.Discount != 0)
                {
                    return $"Скидка: {Discount}%";
                }
                else return null;
            }

        }

        public string TotalPrice
        {
            get
            {
                if (this.Discount != 0)
                {
                    decimal dics = (decimal)this.Discount.Value / 100m;
                    decimal totalPrice = (decimal)((this.Cost) * (1 - dics));
                    return $"Итого: {Math.Round(totalPrice, 2)} руб.";
                }
                else return null;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceClient> ServiceClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhotos> ServicePhotos { get; set; }
    }
}
